sudo: false

language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

env:
    global:
        secure: XhI4KC5mR/imiHCTCNnxBuOsA2JgIiOUxRrlsYG/lJ/lXe/Dbea7RwNPQ2KJolIDhlUzhJcJSaX8vpHFIhWrxX+YpEFmf/rtdU/4H9/fismp0QAXnjGLofwHDE/JY+8GncEgD5XQXYRsDECpohsncvgwtEASyIZiPYFbSZqgpt1z4z8u8Kt8kpvg6eHdRoiiBrmRbM1u+6zLqNtBknANf0iadcQWOIxVya8wTWVxZnqEO9JLKpR1gz7cT1I9Jl+vHjQK3PgTyywC7OVI5Qf1GVlUnF2qw1in+9T+MfPAGF+dmOHiXn/IWAWJyqlpmWkf5pkQoiOFCorS6QHTir1Lo8U8dmvxTz2VOhCBLNjXOVcuVPzD9YKy7bVQrZK3Svev7s+EruN/8goDc+DhQlFrpkQfQuxohRiQk9f6SA8mcbXZ5RpIOPmaNgEUEcoRxFq9Avaea5TVOibkc5K4+9BJW/ykNZjA2Atoue4TA8OeWeGK1uLY47bF0k4Iu6M+obyj/QNULFzU86CA0/C8QAKiAMYM3kk7/Viv1QcilwEaE0Wmc3ytF05vQHJrKOnr4lZIT9q0em+ZzJfTeQrZbF5P2jXf+I2dor67xWYy5uBMj8KSxKDvid2H0Yt5aX4O9/OXGK2i2XGzkrmdx2okmHEZkCWzisA1xcnK3pgL1Kctch8=

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-ci
    - composer test-ci

after_success:
    - APIGEN=false
    - if [ "$TRAVIS_PHP_VERSION" = '5.6' ] && [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then APIGEN=true; fi
    - if $APIGEN; then BUILD_PATH="$(pwd)"; fi
    - if $APIGEN; then REPOSITORY=${REPOSITORY:-"https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG$.git"}; fi
    - if $APIGEN; then BRANCH=${BRANCH:-"gh-pages"}; fi
    - if $APIGEN; then APIGEN_BUILD_PATH=${APIGEN_BUILD_PATH:-"/tmp/apigen"}; fi
    - if $APIGEN; then GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-"Travis CI"}; fi
    - if $APIGEN; then GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-"travis@travis-ci.org"}; fi
    - if $APIGEN; then git clone --branch "$BRANCH" --depth 1 "$REPOSITORY" "$APIGEN_BUILD_PATH"; fi
    - if $APIGEN; then yes | vendor/bin/apigen generate -d "$APIGEN_BUILD_PATH"; fi
    - if $APIGEN; then cd "$APIGEN_BUILD_PATH" || exit 1; fi
    - if $APIGEN; then git config user.name "$GIT_AUTHOR_NAME"; fi
    - if $APIGEN; then git config user.email "$GIT_AUTHOR_EMAIL"; fi
    - if $APIGEN; then git add -A; fi
    - "if $APIGEN; then git commit -m 'docs: generate API documentation'; fi"
    - if $APIGEN; then git push origin "$BRANCH"; fi
    - if $APIGEN; then cd "$BUILD_PATH"; fi

after_script:
    - vendor/bin/coveralls --verbose

notifications:
    email:
        on_success: never
        on_failure: change
